"""add reminded flag to assignments_cache

Revision ID: acde72d719aa
Revises: 815c8083f96b
Create Date: 2026-08-20 18:51:12.901212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'acde72d719aa'
down_revision: Union[str, None] = '815c8083f96b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments_cache', sa.Column('reminded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments_cache', 'reminded')
    # ### end Alembic commands ###