"""sync schema to CourseBook and Canvas iCal architecture

Revision ID: d10830acd31f
Revises: b1211bdf817f
Create Date: 2026-08-14 02:25:30.450448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd10830acd31f'
down_revision: Union[str, None] = 'b1211bdf817f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_sections',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('term', sa.String(length=10), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.Column('section', sa.String(length=10), nullable=False),
    sa.Column('course_title', sa.String(length=255), nullable=True),
    sa.Column('instructor', sa.String(length=255), nullable=True),
    sa.Column('days', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.String(length=20), nullable=True),
    sa.Column('end_time', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('syllabi',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('calendar_cache')
    op.add_column('assignments_cache', sa.Column('canvas_uid', sa.String(length=255), nullable=False))
    op.add_column('assignments_cache', sa.Column('description', sa.Text(), nullable=True))
    op.drop_constraint('assignments_cache_canvas_assignment_id_key', 'assignments_cache', type_='unique')
    op.create_unique_constraint(None, 'assignments_cache', ['canvas_uid'])
    op.drop_column('assignments_cache', 'course_id')
    op.drop_column('assignments_cache', 'points_possible')
    op.drop_column('assignments_cache', 'submitted')
    op.drop_column('assignments_cache', 'canvas_assignment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments_cache', sa.Column('canvas_assignment_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('assignments_cache', sa.Column('submitted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('assignments_cache', sa.Column('points_possible', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('assignments_cache', sa.Column('course_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'assignments_cache', type_='unique')
    op.create_unique_constraint('assignments_cache_canvas_assignment_id_key', 'assignments_cache', ['canvas_assignment_id'])
    op.drop_column('assignments_cache', 'description')
    op.drop_column('assignments_cache', 'canvas_uid')
    op.create_table('calendar_cache',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('google_event_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('calendar_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('start_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('all_day', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('raw_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='calendar_cache_pkey'),
    sa.UniqueConstraint('google_event_id', name='calendar_cache_google_event_id_key')
    )
    op.drop_table('syllabi')
    op.drop_table('course_sections')
    # ### end Alembic commands ###